//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyKobiPL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BillDocument()
        {
            this.CustomerRequests1 = new HashSet<CustomerRequest>();
        }
    
        public string Id { get; set; }
        public string FileName { get; set; }
        public byte[] FileBinary { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CustomerRequest> CustomerRequests1 { get; set; }
    }
}
