//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnergyKobiPL.DBContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendEmailAddress
    {
        public int Id { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<bool> IsCC { get; set; }
    }
}
